url: https://zachhco.github.io

# Site settings
title: Siphekela Isizwe Empowerment and Feeding Scheme
email: Siphekela.Isizwe@gmail.com
description: Our mission is to eradicate poverty in the community at large. We aim to provide food security to underprivileged and impoverished of communities


# Team names, titles and social links
people:
- name: Lungisa Haai
  pic: 1
  position: Founder and CEO
  social:
    - title: instagram
      url: https://www.instagram.com/siphekela.isizwe/
    - title: facebook
      url: https://www.facebook.com/profile.php?id=100067778174081



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/siphekela.isizwe/
  - title: facebook
    url: https://www.facebook.com/profile.php?id=100067778174081

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty